### ISSUE TITLE
Adobe's Flashplayer tgz has changed

### ISSUE THREAD

**Issue by egrath** [flathub/com.adobe.Flash-Player-Projector#13]
Flatpak installation does no longer work as adobe's flashplayer download url has been updated with a new version. New version has hash "6fef160ab61d86ef3d9b6e5740bbd2bcaf33c89cdf0398bb3272bdfd6a636f5b"

**Comment by hadess** [comment]
Fix will be available shortly.

> New version has hash "6fef160ab61d86ef3d9b6e5740bbd2bcaf33c89cdf0398bb3272bdfd6a636f5b"

Note that I would also need the new size of the archive, and the full version number and the file's release date in addition to the hash, so don't feel the need to provide it.

Thanks for the report!
