### ISSUE TITLE
New Version: 32.0.0.192

### ISSUE THREAD

**Issue by egrath** [flathub/com.adobe.Flash-Player-Projector#15]
Adobe has recently bumped the version, so it's currently broken.

New version: 32.0.0.192
Release date: 05/14/2019
sha256sum: 79f4f0386aca44322d02c9e5a8564f97970639bcd866bf173ca0bea7061adf62
size: 8509255

**Comment by hadess** [comment]
Thanks very much for the details, that made it easier :)
