### ISSUE TITLE
Can't Download

### ISSUE THREAD

**Issue by kyle0pan** [flathub/com.adobe.Flash-Player-Projector#23]
```
Kyle@clr-30f5fe0b6cb54580945a1469722205d3~ $ flatpak install flathub com.adobe.Flash-Player-Projector
Looking for matches…

com.adobe.Flash-Player-Projector permissions:
    ipc                  pulseaudio      x11      dri
    file access [1]      tags [2]

    [1] host:ro, xdg-run/gvfs:ro
    [2] proprietary


        ID                                      Arch   Branch Remote  Download
 1. [✗] com.adobe.Flash-Player-Projector        x86_64 stable flathub   8.5 MB / 11.3 MB
 2. [ ] com.adobe.Flash_Player_Projector.Locale x86_64 stable flathub < 6.3 MB (partial)

Error: Wrong size for extra data https://fpdownload.macromedia.com/pub/flashplayer/updaters/32/flash_player_sa_linux.x86_64.tar.gz
error: Failed to install com.adobe.Flash-Player-Projector: Wrong size for extra data https://fpdownload.macromedia.com/pub/flashplayer/updaters/32/flash_player_sa_linux.x86_64.tar.gz
```

The above is what prints out in terminal

**Comment by hadess** [comment]
I don't see it. I have a script running to warn me about those changes, and it didn't trigger.

https://github.com/flathub/com.adobe.Flash-Player-Projector/blob/b2e595faa30e89b3716c93dd7a7f573722869be7/com.adobe.Flash-Player-Projector.json#L54

```sh
$ sha256sum flash_player_sa_linux.x86_64.tar.gz 
258c1d16cb0467ade3fa6c8d3e94ef2c409fca355dba7a39d71c69f0427fdb65  flash_player_sa_linux.x86_64.tar.gz
```

My guess is that you're behind a proxy, or some place with a Wi-Fi hotspot.

What do you actually get downloading https://fpdownload.macromedia.com/pub/flashplayer/updaters/32/flash_player_sa_linux.x86_64.tar.gz directly?

**Comment by kyle0pan** [comment]
I used 'flatpak install flathub com.adobe.Flash-Player-Projector' to download. 

Also, how do I set up and use it from https://fpdownload.macromedia.com/pub/flashplayer/updaters/32/flash_player_sa_linux.x86_64.tar.gz ?

**Comment by hadess** [comment]
The updated package 12 days ago silently failed to build in the buildbot, and thus didn't appear on the Flathub site. That should be done soon. You should see the "32.0.0.255" version showing up on:
https://flathub.org/apps/details/com.adobe.Flash-Player-Projector
