### ISSUE TITLE
Question. Can you build Adobe Acrobat Reader DC flatpak in the future?

### ISSUE THREAD

**Issue by Lvaskz** [flathub/com.adobe.Flash-Player-Projector#5]
Hi, I noticed flash player is in flathub,and I thouth maybe you can build Adobe Acrobat Reader DC . This is a tool really usefull and many people include me, will thank you.
There are plans to do that?

**Comment by TingPing** [comment]
No supported version of Reader supports Linux afaik. Anyway this packages issue is not a place to request new packages.

**Comment by Lvaskz** [comment]
Thanks.

**Comment by arteymix** [comment]
@Lvaskz I've been experimenting with flatpaking Acrobat Reader 9 here https://github.com/arteymix/com.adobe.Reader, but it's broken due to a bad system call. Maybe one of you could take a look?
