### ISSUE TITLE
Adressing the January 12 2021 killswitch

### ISSUE THREAD

**Issue by sm-Fifteen** [flathub/com.adobe.Flash-Player-Projector#53]
Adobe recently updated [their EoL notice for Flash](https://www.adobe.com/ca/products/flashplayer/end-of-life.html) with an indication that Flash Player applications would block all Flash content beginning on January 12 after the EoL date, in order to "help users secure their system" by motivating them further to uninstall Flash.

It is not clear how this affects the Flash Projector and other wrappers such as Flashpoint or the Newgounds player (the notice only mentions "Flash Player"), but assuming this package is meant to remain available past the Flash expiration date, something should probably be done to try and prevent this from activating.

**EDIT:** According to [this reply on the official Flash forum](https://community.adobe.com/t5/flash-player/will-there-be-any-way-to-view-swf-files-locally-after-flash-eol/td-p/11671683?page=1), the standalone player and debugger are indeed affected.

> Flash Player will no longer load content from the open web after Jan 12, 2020.  This includes the debugger and standalone player.  I'm not sure about the bundled .exe files.  If you want to test it, you can set the date forward to Jan 13, 2020 and see what happens.
> 
> For local file and intranet playback, you can use the Enterprise Enablement features to allow local content playback after January 12th.  Again, I'd recommend setting the clock forward and testing your critical use-cases.  We've already shipped the last Flash Player, so you'll need to find workarounds (or contract with HARMAN) if the existing functionality doesn't meet your needs.

**Comment by sm-Fifteen** [comment]
According to their [enterprise FAQ on Flash EoL](https://www.adobe.com/products/flashplayer/enterprise-end-of-life.html) and [page 31 of their Administration Guide](https://www.adobe.com/content/dam/acom/en/devnet/flashplayer/articles/flash_player_admin_guide/pdf/latest/flash_player_32_0_admin_guide.pdf#page=36):

> After Flash Player EOL, `EnableAllowList` will default to true and the MMS.CFG setting will be ignored.

> [`EnableAllowList`] [a]llows system administrators to allow Flash Player to only load content from a set of allowed URLs.

By the looks of it, `AllowListUrlPattern` will then have to specify a whitelist of URL patterns for all SWF files that should still be allowed to run.

**Comment by hadess** [comment]
I don't think much of this applies to the "Flash Player Projector", but I've added the latest version of the tarball to the Web Archive, should the original tarball disappear, and I'll update that if any new releases are made.

**Comment by hadess** [comment]
> Flash Player will no longer load content from the open web after Jan 12, 2020. This includes the debugger and standalone player.

We don't have access to the network, so that's not a problem for us.

**Comment by Hexstream** [comment]
Surprisingly enough, I can confirm that the official Flash Player projector still [works for me](https://www.hexstream.net/#23_february_2021) on Linux.

**Comment by sm-Fifteen** [comment]
Yes, people from various corners of the internet confirmed that this only targeted the browser plugin and worked on a system clock check that forced the activation of some kind of "whitelisted-only" parameter. The flash projector, neither the standalone one or the flatpak one, are affected.

Closing this issue.

**Comment by Hexstream** [comment]
I believe this is extremely not well-known, though.

Tons of people seemed to confirm that the standalone projector WAS affected by the killswitch.
