### ISSUE TITLE
Display issues with Flash Player Standalone

### ISSUE THREAD

**Issue by TheHENOOB** [flathub/com.adobe.Flash-Player-Projector#65]
![image](https://github.com/flathub/com.adobe.Flash-Player-Projector/assets/74883505/5008769f-bd13-4aa2-bf0c-3aeace76ab2d)

This is [BFXR](https://www.bfxr.net/), .swf file downloaded straight from it's own website
https://www.bfxr.net/Bfxr_Flash.swf

When animation happens on the runtime, the display starts to glitch out.
(Loading screen and Mouse Over Button frames)

I am using Linux Mint 21.2 Victoria.

**Comment by hadess** [comment]
I can't reproduce those bugs locally.

I'm afraid that I don't have any good solution for your problem, the Flash Player is dead upstream, and I don't have access to the sources for the BFXR app. Trying to load the Windows version of the tool just crashed the player, which is a bit of a shame. Your best bet would be to report the exact reproducer steps to the application author, nothing else I can do about it.

**Comment by TheHENOOB** [comment]
BFXR is open source by the way:
https://github.com/increpare/bfxr

**Comment by TheHENOOB** [comment]
and I found out that my issues aren't limited to BFXR

Escaping the Prison:
![image](https://github.com/flathub/com.adobe.Flash-Player-Projector/assets/74883505/aaf1b007-088e-4c45-a921-755cd301526c)

**Comment by TheHENOOB** [comment]
> I would say that using the stock GTK+ theme might be a good start.

I am pretty sure my config is on the stock GTK+ theme, there is anything that differs from the GTK default theme to my screenshot?

**Comment by TheHENOOB** [comment]
> > I would say that using the stock GTK+ theme might be a good start.
> 
> I am pretty sure my config is on the stock GTK+ theme, there is anything that differs from the GTK default theme to my screenshot?
> 
> Except of the window title bar at the top which is something from the Cinnamon WM itself.

I found out, when I used the adwaita theme on cinnamon, the player stopped the display glitch, I will report this issue to Linux Mint or Cinnamon devs.

I'll be closing this issue as it doesn't seem to be related to the player.
