### ISSUE TITLE
.swf extension

### ISSUE THREAD

**Issue by PavanLuca** [flathub/com.adobe.Flash-Player-Projector#68]
The player is supposed to run only .spl files but I can also run .swf files so maybe you have to add this file format to get rid of my other 2 issues I reported previously.
![Schermata da 2023-08-25 10-43-31](https://github.com/flathub/com.adobe.Flash-Player-Projector/assets/123581658/9909773d-af86-4185-84b5-0d632bb24655)

**Comment by hadess** [comment]
That's not what the screenshot says. `*.spl` is just another glob for Flash files.
